### ISSUE TITLE
Make a unified login button API

### ISSUE THREAD

**Issue by macfeaster** [datasektionen/Methone#5]
Currently, there is no unified API for the login button.

Since login functionality is provided by the various microservices, my question is whether the login button should actually feature any functionality itself, or if both button text and click href should be provided by the system.

This would solve various ugly hacks used to inject other login providers than login2, while also hiding sensitive API keys. For example, a system would either provide the login endpoint URL, or a surname together with a logout/member dashboard link.

**Comment by danielsson** [comment]
At the moment there is actually two exposed, but undocumented, methods, setLoginButtonText and setLoginButtonClickHandler. The api also states that supplying null to settext hides the button altogether. However Im ambivalent about whether  this is a good model, or if the API should be changed to a getLoginButtonElement call.

**Comment by macfeaster** [comment]
Given that the actual login logic will be handled by each service, the injection approach makes more sense in my opinion. However, system implementors should be consulted before making a final decision.
