### ISSUE TITLE
Methone is always broken in FireFox

### ISSUE THREAD

**Issue by danielsson** [datasektionen/Methone#6]

**Comment by danielsson** [comment]
Varför stödjer vi Firefox ens? #BrowserMonopolyIsGoodRememberIE6

**Comment by aronstrandberg** [comment]
Finns det ens någon vi bryr oss om som använder Firefox?

**Comment by Yopi** [comment]
Alltså. Det vore absurt att inte stödja firefox, som den sista webbläsaren som drivs öppet och för ickeprofit. Jag vet att ni skojar, men ja. Firefox är definitivt en grej!

**Comment by aronstrandberg** [comment]
`-moz-` på allting ba

**Comment by Yopi** [comment]
:shipit:

**Comment by danielsson** [comment]
WONTFIX
