### ISSUE TITLE
Insufficient validation in /enlighten

### ISSUE THREAD

**Issue by macaullyjames** [datasektionen/Methone#8]
The `enlighten/` route performs no input validation on the URL that it's passed. For example,

```
http://methone.froyo.datasektionen.se/enlighten?p=http://google.se
```

will return google.se from the methone.froyo.datasektionen.se domain. This could potentially lead to security issues (cookie theft, information leakage etc.) depending on the configuration of the server. For instance, this exposes any web interfaces that would normally only work on localhost to an attacker (since the request is made from the server).

What's more, I'm pretty sure that passing an invalid URL like this:

```
http://methone.froyo.datasektionen.se/enlighten?p=http://jagfinnsinte.se/
```

Will cause the app to crash and cause a DoS. I was playing around with it today and caused a DoS and I _think_ that's what caused it, but since the app is down I can't reproduce it ^^

I'd like to help out with a PR but I'm not sure how Methone is supposed to be used (this is the first I've heard of it) so I'm a bit lost. Maybe pass a domain to `index.js` at startup and only allow URLs from that domain? :)

**Comment by danielsson** [comment]
Thanks @macaullyjamesmuir for the excellent bug report! The enlighten function has been removed.

Background: Enlighten was a joke intended to force the usage of methone across all our services.

**Comment by macaullyjames** [comment]
No problem :)
