### ISSUE TITLE
Add green infobox

### ISSUE THREAD

**Issue by danielsson** [datasektionen/Methone#9]
The green infobox in the old website is quite good looking. It should be implemented wide across the systems. Methone is the perfect conduit for the gospel.

**Comment by Yopi** [comment]
Näe jag tror inte det va.

**Comment by danielsson** [comment]
Oj, här har något blivit fel!

**Comment by Yopi** [comment]
Någon måtta får det vara iallafall.

**Comment by danielsson** [comment]
ni har rätt
det här borde vara en egen tjänst

**Comment by Yopi** [comment]
Absolut. En så kallad SaaS. 🐴

**Comment by danielsson** [comment]
Shit as a service?
